apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: subscription-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: subscription-hpa
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 20